language: go
go:
  - 1.6
script:
  - make all
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - dists/dev-server-linux.tar.gz
    - dists/dev-server-darwin.tar.gz
    - dists/dev-server-windows.tar.gz
  skip_cleanup: true
  on:
    tags: true
